language: node_js
node_js:
  - "12.17.0"

branches:
  only:
    - infra_spike_travis

before_script:
  - npm install

script:
  - npm run build

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - sed -i '/.next/d' .gitignore
  - git add . && git commit -m "latest build"

deploy:
  - provider: elasticbeanstalk
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    region: "us-east-1"
    app: "infra_spike_travis"
    env: "Infraspiketravis-env"
    bucket_name: ${AWS_S3_BUCKET}
    on:
      branch: "infra_spike_travis"

after_deploy:
  - echo "Application Deployed!"
