language: node_js
node_js:
  - "11.6.0"
branches:
  only:
    - master
before_script:
  - npm install
script:
  - npm run build
  - rm dist -r dist
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - sed -i '/.next/d' .gitignore
  - git add . && git commit -m "latest build"

deploy:
  - provider: elasticbeanstalk
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    region: "us-east-1"
    app: "is_app_cicd_test"
    env: "Isappcicdtest-env"
    bucket_name: ${AWS_S3_BUCKET}
    on:
      branch: "master"

after_deploy:
  - echo "Application Deployed!"
